package:
  name: easyaccess
  version: "1.4.4"

source:
  git_rev: 1.4.4
  git_url: https://github.com/mgckind/easyaccess.git

build:
  number: 0
  preserve_egg_dir: True
  no_link:
    - bin/*
  script: python setup.py install --single-version-externally-managed --record=record.txt
 #noarch_python: True


requirements:
  build:
    - python
    - future >=0.15.0
    - requests
    - termcolor >=1.1.0
    - fitsio >=0.9.11
    - pandas >=0.14
    - oracle-instantclient ==11.2.0.4.0
    - cx_oracle ==5.3
    - numpy
    - python-dateutil

  run:
    - python
    - future >=0.15.0
    - requests
    - termcolor >=1.1.0
    - fitsio >=0.9.11
    - pandas >=0.14
    - oracle-instantclient ==11.2.0.4.0
    - cx_oracle ==5.3
    - numpy
    - python-dateutil

test:
  # Python imports
  imports:
    #- easyaccess
    - cx_Oracle
    - fitsio

about:
  home: https://github.com/mgckind/easyaccess
  license: University of Illinois/NCSA Open Source License
  license_file: LICENSE.txt
  summary: 'Python command line interpreter to access DES Oracle database'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
